BEGIN;

CREATE TABLE IF NOT EXISTS ROUTES(

    ID INTEGER NOT NULL AUTO_INCREMENT,
    ORIGIN VARCHAR(50) NOT NULL,
    DESTINATION VARCHAR(50),
    DISTANCE INTEGER,
    CREATED_AT DATETIME NOT NULL DEFAULT NOW(),
    UPDATED_AT DATETIME,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (ID)

);

CREATE TABLE IF NOT EXISTS USERS(

    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50),
    CITY VARCHAR(50),
    ADDRESS VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    FLIGHT INTEGER NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT NOW(),
    UPDATED_AT DATETIME,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    UNIQUE (EMAIL),
    FOREIGN KEY (FLIGHT) REFERENCES FLIGHTS(ID)

);

CREATE TABLE IF NOT EXISTS FLIGHTS(

    ID INTEGER NOT NULL PRIMARY KEY,
    ROUTE INTEGER NOT NULL REFERENCES ROUTES(ID),
    PLANE INTEGER NOT NULL REFERENCES PLANES(ID),
    TAKEOFF_TIME DATETIME,
    LANDING_TIME DATETIME,
    BOARDING_GATE VARCHAR(50) NOT NULL,
    STATE VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT NOW(),
    UPDATED_AT DATETIME,
    IS_ACTIVE BOOLEAN DEFAULT TRUE
    UNIQUE (EMAIL)
    FOREIGN KEY (ROUTE) REFERENCES ROUTES(ID)
    FOREIGN KEY (PLANE) REFERENCES PLANES(ID)

);

CREATE TABLE IF NOT EXISTS PLANES(

    ID INTEGER NOT NULL PRIMARY KEY,
    MODEL VARCHAR(50) NOT NULL,
    CAPACITY VARCHAR(50) NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT NOW(),
    UPDATED_AT DATETIME,
    IS_ACTIVE BOOLEAN DEFAULT TRUE

);

COMMIT;