-- MySQL Script generated by MySQL Workbench
-- Sat Mar  6 13:44:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AeroPlatzi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AeroPlatzi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AeroPlatzi` ;
USE `AeroPlatzi` ;

-- -----------------------------------------------------
-- Table `AeroPlatzi`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AeroPlatzi`.`User` ;

CREATE TABLE IF NOT EXISTS `AeroPlatzi`.`User` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AeroPlatzi`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AeroPlatzi`.`Country` ;

CREATE TABLE IF NOT EXISTS `AeroPlatzi`.`Country` (
  `CountryId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`CountryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AeroPlatzi`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AeroPlatzi`.`City` ;

CREATE TABLE IF NOT EXISTS `AeroPlatzi`.`City` (
  `CityId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `CountryId` INT NOT NULL,
  PRIMARY KEY (`CityId`),
  INDEX `fk_City_Country1_idx` (`CountryId` ASC),
  CONSTRAINT `fk_City_Country1`
    FOREIGN KEY (`CountryId`)
    REFERENCES `AeroPlatzi`.`Country` (`CountryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AeroPlatzi`.`Route`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AeroPlatzi`.`Route` ;

CREATE TABLE IF NOT EXISTS `AeroPlatzi`.`Route` (
  `RouteId` INT NOT NULL AUTO_INCREMENT,
  `CityId_Origen` INT NOT NULL,
  `CityId_Destiny` INT NOT NULL,
  PRIMARY KEY (`RouteId`),
  INDEX `fk_Route_City1_idx` (`CityId_Origen` ASC),
  INDEX `fk_Route_City2_idx` (`CityId_Destiny` ASC),
  CONSTRAINT `fk_Route_City1`
    FOREIGN KEY (`CityId_Origen`)
    REFERENCES `AeroPlatzi`.`City` (`CityId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Route_City2`
    FOREIGN KEY (`CityId_Destiny`)
    REFERENCES `AeroPlatzi`.`City` (`CityId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AeroPlatzi`.`Plane`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AeroPlatzi`.`Plane` ;

CREATE TABLE IF NOT EXISTS `AeroPlatzi`.`Plane` (
  `PlaneId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) NULL,
  `Capacity` INT NULL,
  PRIMARY KEY (`PlaneId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AeroPlatzi`.`Status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AeroPlatzi`.`Status` ;

CREATE TABLE IF NOT EXISTS `AeroPlatzi`.`Status` (
  `StatusId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`StatusId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AeroPlatzi`.`Flight`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AeroPlatzi`.`Flight` ;

CREATE TABLE IF NOT EXISTS `AeroPlatzi`.`Flight` (
  `FlightId` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NULL,
  `Time` TIME NULL,
  `RouteId` INT NOT NULL,
  `PlaneId` INT NOT NULL,
  `StatusId` INT NOT NULL,
  `NumPassanger` INT NULL,
  PRIMARY KEY (`FlightId`),
  INDEX `fk_Flight_Route1_idx` (`RouteId` ASC),
  INDEX `fk_Flight_Plane1_idx` (`PlaneId` ASC),
  INDEX `fk_Flight_Status1_idx` (`StatusId` ASC),
  CONSTRAINT `fk_Flight_Route1`
    FOREIGN KEY (`RouteId`)
    REFERENCES `AeroPlatzi`.`Route` (`RouteId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Plane1`
    FOREIGN KEY (`PlaneId`)
    REFERENCES `AeroPlatzi`.`Plane` (`PlaneId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Flight_Status1`
    FOREIGN KEY (`StatusId`)
    REFERENCES `AeroPlatzi`.`Status` (`StatusId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AeroPlatzi`.`FlightUsers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AeroPlatzi`.`FlightUsers` ;

CREATE TABLE IF NOT EXISTS `AeroPlatzi`.`FlightUsers` (
  `FlightUsers` INT NOT NULL AUTO_INCREMENT,
  `UserId` INT NOT NULL,
  `FlightId` INT NOT NULL,
  PRIMARY KEY (`FlightUsers`),
  INDEX `fk_FlightUsers_User1_idx` (`UserId` ASC),
  INDEX `fk_FlightUsers_Flight1_idx` (`FlightId` ASC),
  CONSTRAINT `fk_FlightUsers_User1`
    FOREIGN KEY (`UserId`)
    REFERENCES `AeroPlatzi`.`User` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FlightUsers_Flight1`
    FOREIGN KEY (`FlightId`)
    REFERENCES `AeroPlatzi`.`Flight` (`FlightId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
